### ISSUE TITLE
CIを実施できるようにする

### ISSUE THREAD

**Issue by atsushimemet** [atsushimemet/vook_web_v3#16]
# 進め方例
1. .github/workflows ディレクトリを作成する。
2. spec ディレクトリ内のテストコードを実行するジョブを定義するためのYAMLファイルを作成する。

例えば、以下のような .github/workflows/rspec.yml ファイルを作成

```

name: RSpec

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp_test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Build and test
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/myapp_test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake db:schema:load
        bundle exec rspec spec/

```
上記参考に、開発環境(将矢個人アカウント)と本番環境(古賀アカウント)を念頭に入れつつ、ymlを書く。

# 他
- まずは、CIまでできるようにする。
- ER作成待ちの時間にやれると良い
